<?php
	function hislider1_menu(){
	  $items = array();
 
	  $items['hislider1'] = array(
	    'title'            => t('GNDEC'),
	    'page callback'    => 'hislider1_output',
	    'access arguments' => array('access content'),
	  );
	  
	  return $items;
	}
 
	function hislider1_init(){
		
		$drupal_version = 6;
		if ( $drupal_version == '7' )
		{
			$module_path = base_path() . drupal_get_path('module', 'hislider1');
		}
		else
		{
			$module_path = drupal_get_path('module', 'hislider1');
		}
		drupal_add_js( $module_path . '/js/jquery.js');
		drupal_add_js( $module_path . '/js/jquery.hislider.js');
	}
	
	function hislider1_output() {
		
		$module_path = base_path() . drupal_get_path('module', 'hislider1');
		$html_codes = '    
     <!-- Insert to your webpage where you want to display the slider -->
    <div id="hislider1" style="width:400px;height:300px;overflow:hidden; margin: 0 auto;">
    <noscript>The slider is powered by <strong>Hi Slider</strong>, a easy jQuery image slider from <a target="_blank" href="hislider.com">hislider.com</a>. Please enable JavaScript to view.</noscript><div class="hi-about-text" style="display:none">This jQuery slider was created with the free <a style="color:#FFF;" href="http://hislider.com" target="_blank">Hi Slider</a> for WordPress plugin,Joomla & Drupal Module from hislider.com.<br /><br /><a style="color:#FFF;" href="#" class="hi-about-ok">OK</a></div><div class="hi-slider-watermark"  style="display:none"><a href="http://hislider.com" target="_blank">hislider.com</a></div>
    <script type="text/javascript">var hiSliderJsFolder="' . $module_path . '/"</script>
    </div>
    
';															
		
		return $html_codes;
	}
?>
